Vagrant.configure("2") do |config|
  config.vm.box = "kalilinux/rolling"
  config.vm.hostname = "red"
  config.vm.network "private_network", ip: "192.168.62.110"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "red-kali"
    vb.memory = 2048
    vb.cpus = 2
  end
end
